# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vbW_PQ6vgew-1y1Oarydjg5KclEq1c1i
"""

import streamlit as st
import pickle
from sklearn.feature_extraction.text import CountVectorizer

# Load the trained model and CountVectorizer
with open('model_lr_m.h5', 'rb') as model_file, open('count_vec.h5', 'rb') as vectorizer_file:
    model = pickle.load(model_file)
    vectorizer = pickle.load(vectorizer_file)

# Create a Streamlit web app
st.title("Multi-Label Comment Classification")

# Create a text input field for user comments
user_input = st.text_area("Enter your comment here:")

# Create a "Predict" button
if st.button("Predict"):
    if user_input:
        # Preprocess the user's input text using the loaded CountVectorizer
        user_input_cv = vectorizer.transform([user_input])

        # Make predictions using the loaded model
        predictions = model.predict(user_input_cv)

        # Create a dictionary to map the labels to their respective names
        label_names = {
            0: 'Toxic',
            1: 'Severe Toxic',
            2: 'Obscene',
            3: 'Threat',
            4: 'Insult',
            5: 'Identity Hate'
        }

        # Display the predicted labels
        st.subheader("Predicted Labels:")
        for i, label_id in enumerate(label_names):
            label_name = label_names[label_id]
            prediction = "Yes" if predictions[0, i] == 1 else "No"
            st.write(f"{label_name}: {prediction}")

# Run the Streamlit app
if __name__ == '__main__':
    st.set_option('deprecation.showfileUploaderEncoding', False)
    st.set_option('deprecation.showPyplotGlobalUse', False)